# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/KooChemicalSimulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/KooChemicalSimulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/KooChemicalSimulation/CMakeFiles /home/user/KooChemicalSimulation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/KooChemicalSimulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_interfaces_compile

# Build rule for target.
test_interfaces_compile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_interfaces_compile
.PHONY : test_interfaces_compile

# fast build rule for target.
test_interfaces_compile/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/test_interfaces_compile.dir/build.make core/CMakeFiles/test_interfaces_compile.dir/build
.PHONY : test_interfaces_compile/fast

#=============================================================================
# Target rules for targets named test_phase3

# Build rule for target.
test_phase3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase3
.PHONY : test_phase3

# fast build rule for target.
test_phase3/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase3.dir/build.make tests/unit/CMakeFiles/test_phase3.dir/build
.PHONY : test_phase3/fast

#=============================================================================
# Target rules for targets named test_phase4

# Build rule for target.
test_phase4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase4
.PHONY : test_phase4

# fast build rule for target.
test_phase4/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase4.dir/build.make tests/unit/CMakeFiles/test_phase4.dir/build
.PHONY : test_phase4/fast

#=============================================================================
# Target rules for targets named test_phase5

# Build rule for target.
test_phase5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase5
.PHONY : test_phase5

# fast build rule for target.
test_phase5/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase5.dir/build.make tests/unit/CMakeFiles/test_phase5.dir/build
.PHONY : test_phase5/fast

#=============================================================================
# Target rules for targets named test_phase6

# Build rule for target.
test_phase6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase6
.PHONY : test_phase6

# fast build rule for target.
test_phase6/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase6.dir/build.make tests/unit/CMakeFiles/test_phase6.dir/build
.PHONY : test_phase6/fast

#=============================================================================
# Target rules for targets named test_phase7

# Build rule for target.
test_phase7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase7
.PHONY : test_phase7

# fast build rule for target.
test_phase7/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase7.dir/build.make tests/unit/CMakeFiles/test_phase7.dir/build
.PHONY : test_phase7/fast

#=============================================================================
# Target rules for targets named test_phase8

# Build rule for target.
test_phase8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase8
.PHONY : test_phase8

# fast build rule for target.
test_phase8/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase8.dir/build.make tests/unit/CMakeFiles/test_phase8.dir/build
.PHONY : test_phase8/fast

#=============================================================================
# Target rules for targets named test_phase9

# Build rule for target.
test_phase9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase9
.PHONY : test_phase9

# fast build rule for target.
test_phase9/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase9.dir/build.make tests/unit/CMakeFiles/test_phase9.dir/build
.PHONY : test_phase9/fast

#=============================================================================
# Target rules for targets named test_phase10

# Build rule for target.
test_phase10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase10
.PHONY : test_phase10

# fast build rule for target.
test_phase10/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase10.dir/build.make tests/unit/CMakeFiles/test_phase10.dir/build
.PHONY : test_phase10/fast

#=============================================================================
# Target rules for targets named test_phase11

# Build rule for target.
test_phase11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase11
.PHONY : test_phase11

# fast build rule for target.
test_phase11/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase11.dir/build.make tests/unit/CMakeFiles/test_phase11.dir/build
.PHONY : test_phase11/fast

#=============================================================================
# Target rules for targets named test_phase12

# Build rule for target.
test_phase12: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase12
.PHONY : test_phase12

# fast build rule for target.
test_phase12/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase12.dir/build.make tests/unit/CMakeFiles/test_phase12.dir/build
.PHONY : test_phase12/fast

#=============================================================================
# Target rules for targets named test_phase13

# Build rule for target.
test_phase13: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase13
.PHONY : test_phase13

# fast build rule for target.
test_phase13/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase13.dir/build.make tests/unit/CMakeFiles/test_phase13.dir/build
.PHONY : test_phase13/fast

#=============================================================================
# Target rules for targets named test_phase14

# Build rule for target.
test_phase14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase14
.PHONY : test_phase14

# fast build rule for target.
test_phase14/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase14.dir/build.make tests/unit/CMakeFiles/test_phase14.dir/build
.PHONY : test_phase14/fast

#=============================================================================
# Target rules for targets named test_phase16

# Build rule for target.
test_phase16: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase16
.PHONY : test_phase16

# fast build rule for target.
test_phase16/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase16.dir/build.make tests/unit/CMakeFiles/test_phase16.dir/build
.PHONY : test_phase16/fast

#=============================================================================
# Target rules for targets named test_phase17

# Build rule for target.
test_phase17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase17
.PHONY : test_phase17

# fast build rule for target.
test_phase17/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase17.dir/build.make tests/unit/CMakeFiles/test_phase17.dir/build
.PHONY : test_phase17/fast

#=============================================================================
# Target rules for targets named test_phase18

# Build rule for target.
test_phase18: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase18
.PHONY : test_phase18

# fast build rule for target.
test_phase18/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase18.dir/build.make tests/unit/CMakeFiles/test_phase18.dir/build
.PHONY : test_phase18/fast

#=============================================================================
# Target rules for targets named test_phase19

# Build rule for target.
test_phase19: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase19
.PHONY : test_phase19

# fast build rule for target.
test_phase19/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase19.dir/build.make tests/unit/CMakeFiles/test_phase19.dir/build
.PHONY : test_phase19/fast

#=============================================================================
# Target rules for targets named test_phase20

# Build rule for target.
test_phase20: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase20
.PHONY : test_phase20

# fast build rule for target.
test_phase20/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase20.dir/build.make tests/unit/CMakeFiles/test_phase20.dir/build
.PHONY : test_phase20/fast

#=============================================================================
# Target rules for targets named test_phase21

# Build rule for target.
test_phase21: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase21
.PHONY : test_phase21

# fast build rule for target.
test_phase21/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase21.dir/build.make tests/unit/CMakeFiles/test_phase21.dir/build
.PHONY : test_phase21/fast

#=============================================================================
# Target rules for targets named test_phase22

# Build rule for target.
test_phase22: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase22
.PHONY : test_phase22

# fast build rule for target.
test_phase22/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase22.dir/build.make tests/unit/CMakeFiles/test_phase22.dir/build
.PHONY : test_phase22/fast

#=============================================================================
# Target rules for targets named test_phase23

# Build rule for target.
test_phase23: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase23
.PHONY : test_phase23

# fast build rule for target.
test_phase23/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase23.dir/build.make tests/unit/CMakeFiles/test_phase23.dir/build
.PHONY : test_phase23/fast

#=============================================================================
# Target rules for targets named test_phase24_26

# Build rule for target.
test_phase24_26: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase24_26
.PHONY : test_phase24_26

# fast build rule for target.
test_phase24_26/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase24_26.dir/build.make tests/unit/CMakeFiles/test_phase24_26.dir/build
.PHONY : test_phase24_26/fast

#=============================================================================
# Target rules for targets named test_phase31_35

# Build rule for target.
test_phase31_35: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase31_35
.PHONY : test_phase31_35

# fast build rule for target.
test_phase31_35/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase31_35.dir/build.make tests/unit/CMakeFiles/test_phase31_35.dir/build
.PHONY : test_phase31_35/fast

#=============================================================================
# Target rules for targets named test_phase36_40

# Build rule for target.
test_phase36_40: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase36_40
.PHONY : test_phase36_40

# fast build rule for target.
test_phase36_40/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase36_40.dir/build.make tests/unit/CMakeFiles/test_phase36_40.dir/build
.PHONY : test_phase36_40/fast

#=============================================================================
# Target rules for targets named test_phase41_45

# Build rule for target.
test_phase41_45: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase41_45
.PHONY : test_phase41_45

# fast build rule for target.
test_phase41_45/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase41_45.dir/build.make tests/unit/CMakeFiles/test_phase41_45.dir/build
.PHONY : test_phase41_45/fast

#=============================================================================
# Target rules for targets named test_phase51

# Build rule for target.
test_phase51: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase51
.PHONY : test_phase51

# fast build rule for target.
test_phase51/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase51.dir/build.make tests/unit/CMakeFiles/test_phase51.dir/build
.PHONY : test_phase51/fast

#=============================================================================
# Target rules for targets named test_phase52

# Build rule for target.
test_phase52: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase52
.PHONY : test_phase52

# fast build rule for target.
test_phase52/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase52.dir/build.make tests/unit/CMakeFiles/test_phase52.dir/build
.PHONY : test_phase52/fast

#=============================================================================
# Target rules for targets named test_phase53

# Build rule for target.
test_phase53: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_phase53
.PHONY : test_phase53

# fast build rule for target.
test_phase53/fast:
	$(MAKE) $(MAKESILENT) -f tests/unit/CMakeFiles/test_phase53.dir/build.make tests/unit/CMakeFiles/test_phase53.dir/build
.PHONY : test_phase53/fast

#=============================================================================
# Target rules for targets named reaction_example

# Build rule for target.
reaction_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reaction_example
.PHONY : reaction_example

# fast build rule for target.
reaction_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/reaction_example.dir/build.make examples/CMakeFiles/reaction_example.dir/build
.PHONY : reaction_example/fast

#=============================================================================
# Target rules for targets named diffusion_example

# Build rule for target.
diffusion_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diffusion_example
.PHONY : diffusion_example

# fast build rule for target.
diffusion_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/diffusion_example.dir/build.make examples/CMakeFiles/diffusion_example.dir/build
.PHONY : diffusion_example/fast

#=============================================================================
# Target rules for targets named surface_example

# Build rule for target.
surface_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 surface_example
.PHONY : surface_example

# fast build rule for target.
surface_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/surface_example.dir/build.make examples/CMakeFiles/surface_example.dir/build
.PHONY : surface_example/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... diffusion_example"
	@echo "... reaction_example"
	@echo "... surface_example"
	@echo "... test_interfaces_compile"
	@echo "... test_phase10"
	@echo "... test_phase11"
	@echo "... test_phase12"
	@echo "... test_phase13"
	@echo "... test_phase14"
	@echo "... test_phase16"
	@echo "... test_phase17"
	@echo "... test_phase18"
	@echo "... test_phase19"
	@echo "... test_phase20"
	@echo "... test_phase21"
	@echo "... test_phase22"
	@echo "... test_phase23"
	@echo "... test_phase24_26"
	@echo "... test_phase3"
	@echo "... test_phase31_35"
	@echo "... test_phase36_40"
	@echo "... test_phase4"
	@echo "... test_phase41_45"
	@echo "... test_phase5"
	@echo "... test_phase51"
	@echo "... test_phase52"
	@echo "... test_phase53"
	@echo "... test_phase6"
	@echo "... test_phase7"
	@echo "... test_phase8"
	@echo "... test_phase9"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

